// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhSsjXViz0AMYFKipbU-dsSGDuBtKS44',
    appId: '1:1077407633101:web:e3fe7a12b7068ae5b1e384',
    messagingSenderId: '1077407633101',
    projectId: 'novel-mn',
    authDomain: 'novel-mn.firebaseapp.com',
    storageBucket: 'novel-mn.firebasestorage.app',
    measurementId: 'G-0S22EDBQ3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFvV_2ov4cNFjR5QH_NIRnGrESjfXONe8',
    appId: '1:1077407633101:android:0fc699ba709ea97eb1e384',
    messagingSenderId: '1077407633101',
    projectId: 'novel-mn',
    storageBucket: 'novel-mn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa8if3117INQHRJQHlq2IOVCUm1KZNjqM',
    appId: '1:1077407633101:ios:631868e2856915a6b1e384',
    messagingSenderId: '1077407633101',
    projectId: 'novel-mn',
    storageBucket: 'novel-mn.firebasestorage.app',
    iosBundleId: 'com.example.novelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa8if3117INQHRJQHlq2IOVCUm1KZNjqM',
    appId: '1:1077407633101:ios:631868e2856915a6b1e384',
    messagingSenderId: '1077407633101',
    projectId: 'novel-mn',
    storageBucket: 'novel-mn.firebasestorage.app',
    iosBundleId: 'com.example.novelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAhSsjXViz0AMYFKipbU-dsSGDuBtKS44',
    appId: '1:1077407633101:web:ff2e39f0edc1dcd3b1e384',
    messagingSenderId: '1077407633101',
    projectId: 'novel-mn',
    authDomain: 'novel-mn.firebaseapp.com',
    storageBucket: 'novel-mn.firebasestorage.app',
    measurementId: 'G-LTX9K9J9FX',
  );
}
